// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnigugglvamhinawageu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaWd1Z2dsdmFtaGluYXdhZ2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODQ0NjEsImV4cCI6MjA2Mzg2MDQ2MX0.7TtrpM2UfGFFkA_5Hu3PIuTbr58B3hYzRRxRvcCPxAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);